<a href="https://colab.research.google.com/github/alvarengagraziela3-oss/Ciencia_Dados_Aprendizagem_Maquina/blob/main/ciencia_dados.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

*Nome: Graziela Alvarenga | Sistemas de informação*

### **Aula 02/09 _ II – Análise e Ciência de Dados**
- Visualização e interpretação de dados
- Aula prática + resolução colaborativa de problemas
- Criar gráficos e interpretar informações obtidas dos dados
- Dashboard ou conjunto de visualizações comentadas




Referência
CARVALHO, André Carlos de; MENEZES, Angelo; BONIDIA, Robson. Ciência de Dados — Fundamentos e
Aplicações. Capítulo “Python para Ciência de Dados”. Disponível em: https://bonidia.github.io/cd-
fundamentos/cp2.html. Acesso em: 2 set. 2026

In [2]:
import pandas as pd

# ==========================================
# 1. Series e DataFrame
# ==========================================

prioridades = pd.Series(
    ["Alta", "Média", "Baixa"],
    name="prioridade"
)

exemplo = pd.DataFrame({
    "id": ["CH001", "CH002"],
    "tempo": [3.5, 12.0]
})

print("SERIES:")
print(prioridades)

print("\nDATAFRAME DE EXEMPLO:")
print(exemplo)


# ==========================================
# 2. Carregamento e inspeção
# ==========================================

df = pd.read_csv("chamados_suporte_ti.csv")

print("\nPRIMEIROS 5 REGISTROS:")
print(df.head())

print("\nÚLTIMOS 3 REGISTROS:")
print(df.tail(3))

print("\nDIMENSÕES:")
print(df.shape)

print("\nCOLUNAS:")
print(df.columns.tolist())

print("\nINFORMAÇÕES:")
df.info()

print("\nESTATÍSTICAS DESCRITIVAS:")
print(df.describe())


# ==========================================
# 3. Seleção
# ==========================================

print("\nCOLUNA SETOR:")
print(df["setor"])

print("\nID E SETOR:")
print(df[["id_chamado", "setor"]])

print("\nLOC:")
print(df.loc[0:2, ["id_chamado", "setor"]])

print("\nILOC:")
print(df.iloc[0:3, 0:2])


# ==========================================
# 4. Filtros
# ==========================================

print("\nPRIORIDADE ALTA:")
print(df[df["prioridade"] == "Alta"])

print("\nPRIORIDADE ALTA E RESOLVIDO:")
print(
    df[
        (df["prioridade"] == "Alta") &
        (df["status"] == "Resolvido")
    ]
)

print("\nCATEGORIAS ACESSO OU REDE:")
print(
    df[
        df["categoria"].isin(["Acesso", "Rede"])
    ]
)


# ==========================================
# 5. Transformações
# ==========================================

df["data_abertura"] = pd.to_datetime(
    df["data_abertura"]
)

df["tempo_dias"] = (
    df["tempo_resolucao_horas"] / 24
)

df["satisfacao"] = df["satisfacao"].astype("Int64")

print("\nDATAFRAME APÓS TRANSFORMAÇÕES:")
print(df.head())


# ==========================================
# 6. Agregações
# ==========================================

print("\nQUANTIDADE POR STATUS:")
print(df["status"].value_counts())

print("\nTEMPO MÉDIO DE RESOLUÇÃO:")
print(df["tempo_resolucao_horas"].mean())

print("\nTEMPO MÉDIO POR CATEGORIA:")
print(
    df.groupby("categoria")[
        "tempo_resolucao_horas"
    ].mean().sort_values(ascending=False)
)

SERIES:
0     Alta
1    Média
2    Baixa
Name: prioridade, dtype: object

DATAFRAME DE EXEMPLO:
      id  tempo
0  CH001    3.5
1  CH002   12.0

PRIMEIROS 5 REGISTROS:
  id_chamado data_abertura       setor        categoria prioridade  \
0      CH001    2026-08-20  Financeiro           Acesso       Alta
1      CH002    2026-08-20   Acadêmico    Sistema lento      Média
2      CH003    2026-08-21  Biblioteca       Impressora      Baixa
3      CH004    2026-08-21  Financeiro  Erro de sistema    Crítica
4      CH005    2026-08-22          RH           Acesso      Média

         status  tempo_resolucao_horas  satisfacao reaberto analista
0     Resolvido                    3.5         5.0      Não      Ana
1     Resolvido                   12.0         4.0      Não    Bruno
2     Resolvido                   30.0         3.0      Sim    Carla
3     Resolvido                    2.0         5.0      Não      Ana
4  Em andamento                    NaN         NaN      Não    Diego

ÚLTIMOS 3 REGISTROS:
   id_chamado data_abertura        setor      categoria prioridade     status  \
15      CH016    2026-08-27   Financeiro         Acesso      Baixa  Resolvido
16      CH017    2026-08-28    Acadêmico       Hardware      Média  Resolvido
17      CH018    2026-08-28  Laboratório  Sistema lento      Média  Resolvido

    tempo_resolucao_horas  satisfacao reaberto analista
15                   52.0         2.0      Sim    Diego
16                   16.0         4.0      Não      Ana
17                  120.0         1.0      Sim    Bruno

DIMENSÕES:
(18, 10)

COLUNAS:
['id_chamado', 'data_abertura', 'setor', 'categoria', 'prioridade', 'status', 'tempo_resolucao_horas', 'satisfacao', 'reaberto', 'analista']

INFORMAÇÕES:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 18 entries, 0 to 17
Data columns (total 10 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   id_chamado             18 non-null     object
 1   data_abertura          18 non-null     object
 2   setor                  18 non-null     object
 3   categoria              18 non-null     object
 4   prioridade             18 non-null     object
 5   status                 18 non-null     object
 6   tempo_resolucao_horas  16 non-null     float64
 7   satisfacao             16 non-null     float64
 8   reaberto               18 non-null     object
 9   analista               18 non-null     object
dtypes: float64(2), object(8)
memory usage: 1.5+ KB

ESTATÍSTICAS DESCRITIVAS:
       tempo_resolucao_horas  satisfacao
count              16.000000   16.000000
mean               23.000000    3.625000
std                29.648496    1.310216
min                 2.000000    1.000000
25%                 6.750000    2.750000
50%                13.000000    4.000000
75%                22.500000    5.000000
max               120.000000    5.000000

COLUNA SETOR:
0      Financeiro
1       Acadêmico
2      Biblioteca
3      Financeiro
4              RH
5       Acadêmico
6     Laboratório
7      Biblioteca
8              RH
9     Laboratório
10     Financeiro
11      Acadêmico
12     Biblioteca
13             RH
14    Laboratório
15     Financeiro
16      Acadêmico
17    Laboratório
Name: setor, dtype: object

ID E SETOR:
   id_chamado        setor
0       CH001   Financeiro
1       CH002    Acadêmico
2       CH003   Biblioteca
3       CH004   Financeiro
4       CH005           RH
5       CH006    Acadêmico
6       CH007  Laboratório
7       CH008   Biblioteca
8       CH009           RH
9       CH010  Laboratório
10      CH011   Financeiro
11      CH012    Acadêmico
12      CH013   Biblioteca
13      CH014           RH
14      CH015  Laboratório
15      CH016   Financeiro
16      CH017    Acadêmico
17      CH018  Laboratório

LOC:
  id_chamado       setor
0      CH001  Financeiro
1      CH002   Acadêmico
2      CH003  Biblioteca

ILOC:
  id_chamado data_abertura
0      CH001    2026-08-20
1      CH002    2026-08-20
2      CH003    2026-08-21

PRIORIDADE ALTA:
   id_chamado data_abertura       setor        categoria prioridade  \
0       CH001    2026-08-20  Financeiro           Acesso       Alta
5       CH006    2026-08-22   Acadêmico             Rede       Alta
8       CH009    2026-08-24          RH  Erro de sistema       Alta
13      CH014    2026-08-26          RH    Sistema lento       Alta

       status  tempo_resolucao_horas  satisfacao reaberto analista
0   Resolvido                    3.5         5.0      Não      Ana
5   Resolvido                    9.5         2.0      Sim    Bruno
8   Resolvido                    7.0         5.0      Não      Ana
13  Resolvido                   14.0         3.0      Sim    Bruno

PRIORIDADE ALTA E RESOLVIDO:
   id_chamado data_abertura       setor        categoria prioridade  \
0       CH001    2026-08-20  Financeiro           Acesso       Alta
5       CH006    2026-08-22   Acadêmico             Rede       Alta
8       CH009    2026-08-24          RH  Erro de sistema       Alta
13      CH014    2026-08-26          RH    Sistema lento       Alta

       status  tempo_resolucao_horas  satisfacao reaberto analista
0   Resolvido                    3.5         5.0      Não      Ana
5   Resolvido                    9.5         2.0      Sim    Bruno
8   Resolvido                    7.0         5.0      Não      Ana
13  Resolvido                   14.0         3.0      Sim    Bruno

CATEGORIAS ACESSO OU REDE:
   id_chamado data_abertura        setor categoria prioridade        status  \
0       CH001    2026-08-20   Financeiro    Acesso       Alta     Resolvido
4       CH005    2026-08-22           RH    Acesso      Média  Em andamento
5       CH006    2026-08-22    Acadêmico      Rede       Alta     Resolvido
9       CH010    2026-08-24  Laboratório      Rede    Crítica     Resolvido
11      CH012    2026-08-25    Acadêmico    Acesso      Baixa     Resolvido
12      CH013    2026-08-26   Biblioteca      Rede      Média     Resolvido
15      CH016    2026-08-27   Financeiro    Acesso      Baixa     Resolvido

    tempo_resolucao_horas  satisfacao reaberto analista
0                     3.5         5.0      Não      Ana
4                     NaN         NaN      Não    Diego
5                     9.5         2.0      Sim    Bruno
9                     6.0         2.0      Sim    Bruno
11                   10.0         5.0      Não    Diego
12                   18.0         4.0      Não      Ana
15                   52.0         2.0      Sim    Diego

DATAFRAME APÓS TRANSFORMAÇÕES:
  id_chamado data_abertura       setor        categoria prioridade  \
0      CH001    2026-08-20  Financeiro           Acesso       Alta
1      CH002    2026-08-20   Acadêmico    Sistema lento      Média
2      CH003    2026-08-21  Biblioteca       Impressora      Baixa
3      CH004    2026-08-21  Financeiro  Erro de sistema    Crítica
4      CH005    2026-08-22          RH           Acesso      Média

         status  tempo_resolucao_horas  satisfacao reaberto analista  \
0     Resolvido                    3.5           5      Não      Ana
1     Resolvido                   12.0           4      Não    Bruno
2     Resolvido                   30.0           3      Sim    Carla
3     Resolvido                    2.0           5      Não      Ana
4  Em andamento                    NaN        <NA>      Não    Diego

   tempo_dias
0    0.145833
1    0.500000
2    1.250000
3    0.083333
4         NaN

QUANTIDADE POR STATUS:
status
Resolvido       16
Em andamento     1
Aberto           1
Name: count, dtype: int64

TEMPO MÉDIO DE RESOLUÇÃO:
23.0

TEMPO MÉDIO POR CATEGORIA:
categoria
Sistema lento      47.750000
Impressora         30.000000
Acesso             21.833333
Hardware           18.000000
Rede               11.166667
Erro de sistema     4.000000
Name: tempo_resolucao_horas, dtype: float64

In [3]:
import pandas as pd

df = pd.read_csv("chamados_suporte_ti.csv")

# Cinco primeiras linhas
df.head()

,id_chamado,data_abertura,setor,categoria,prioridade,status,tempo_resolucao_horas,satisfacao,reaberto,analista
0,CH001,2026-08-20,Financeiro,Acesso,Alta,Resolvido,3.5,5.0,Não,Ana
1,CH002,2026-08-20,Acadêmico,Sistema lento,Média,Resolvido,12.0,4.0,Não,Bruno
2,CH003,2026-08-21,Biblioteca,Impressora,Baixa,Resolvido,30.0,3.0,Sim,Carla
3,CH004,2026-08-21,Financeiro,Erro de sistema,Crítica,Resolvido,2.0,5.0,Não,Ana
4,CH005,2026-08-22,RH,Acesso,Média,Em andamento,NaN,NaN,Não,Diego

In [4]:
# Três últimas linhas
df.tail(3)

,id_chamado,data_abertura,setor,categoria,prioridade,status,tempo_resolucao_horas,satisfacao,reaberto,analista
15,CH016,2026-08-27,Financeiro,Acesso,Baixa,Resolvido,52.0,2.0,Sim,Diego
16,CH017,2026-08-28,Acadêmico,Hardware,Média,Resolvido,16.0,4.0,Não,Ana
17,CH018,2026-08-28,Laboratório,Sistema lento,Média,Resolvido,120.0,1.0,Sim,Bruno

In [5]:
# Dimensões
print(df.shape)

# Nomes das colunas
print(df.columns.tolist())

(18, 10)
['id_chamado', 'data_abertura', 'setor', 'categoria', 'prioridade', 'status', 'tempo_resolucao_horas', 'satisfacao', 'reaberto', 'analista']

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 18 entries, 0 to 17
Data columns (total 10 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   id_chamado             18 non-null     object
 1   data_abertura          18 non-null     object
 2   setor                  18 non-null     object
 3   categoria              18 non-null     object
 4   prioridade             18 non-null     object
 5   status                 18 non-null     object
 6   tempo_resolucao_horas  16 non-null     float64
 7   satisfacao             16 non-null     float64
 8   reaberto               18 non-null     object
 9   analista               18 non-null     object
dtypes: float64(2), object(8)
memory usage: 1.5+ KB

In [7]:
df.describe()

       tempo_resolucao_horas  satisfacao
count              16.000000   16.000000
mean               23.000000    3.625000
std                29.648496    1.310216
min                 2.000000    1.000000
25%                 6.750000    2.750000
50%                13.000000    4.000000
75%                22.500000    5.000000
max               120.000000    5.000000

In [9]:
tempo_resolucao_horas = 120

In [10]:
recorte = df[
    ["id_chamado", "setor", "prioridade", "status"]
]

display(recorte)

   id_chamado        setor prioridade        status
0       CH001   Financeiro       Alta     Resolvido
1       CH002    Acadêmico      Média     Resolvido
2       CH003   Biblioteca      Baixa     Resolvido
3       CH004   Financeiro    Crítica     Resolvido
4       CH005           RH      Média  Em andamento
5       CH006    Acadêmico       Alta     Resolvido
6       CH007  Laboratório      Média     Resolvido
7       CH008   Biblioteca      Baixa     Resolvido
8       CH009           RH       Alta     Resolvido
9       CH010  Laboratório    Crítica     Resolvido
10      CH011   Financeiro      Média        Aberto
11      CH012    Acadêmico      Baixa     Resolvido
12      CH013   Biblioteca      Média     Resolvido
13      CH014           RH       Alta     Resolvido
14      CH015  Laboratório    Crítica     Resolvido
15      CH016   Financeiro      Baixa     Resolvido
16      CH017    Acadêmico      Média     Resolvido
17      CH018  Laboratório      Média     Resolvido

In [11]:
display(recorte.head())

  id_chamado       setor prioridade        status
0      CH001  Financeiro       Alta     Resolvido
1      CH002   Acadêmico      Média     Resolvido
2      CH003  Biblioteca      Baixa     Resolvido
3      CH004  Financeiro    Crítica     Resolvido
4      CH005          RH      Média  Em andamento

In [12]:
posicional = df.iloc[0:5, 0:4]

display(posicional)

  id_chamado data_abertura       setor        categoria
0      CH001    2026-08-20  Financeiro           Acesso
1      CH002    2026-08-20   Acadêmico    Sistema lento
2      CH003    2026-08-21  Biblioteca       Impressora
3      CH004    2026-08-21  Financeiro  Erro de sistema
4      CH005    2026-08-22          RH           Acesso

In [13]:
altos = df[df["prioridade"] == "Alta"]

display(altos)

print("Quantidade:", altos.shape[0])

,id_chamado,data_abertura,setor,categoria,prioridade,status,tempo_resolucao_horas,satisfacao,reaberto,analista
0,CH001,2026-08-20,Financeiro,Acesso,Alta,Resolvido,3.5,5.0,Não,Ana
5,CH006,2026-08-22,Acadêmico,Rede,Alta,Resolvido,9.5,2.0,Sim,Bruno
8,CH009,2026-08-24,RH,Erro de sistema,Alta,Resolvido,7.0,5.0,Não,Ana
13,CH014,2026-08-26,RH,Sistema lento,Alta,Resolvido,14.0,3.0,Sim,Bruno

Quantidade: 4

In [14]:
lentos = df[
    (df["status"] == "Resolvido") &
    (df["tempo_resolucao_horas"] > 24)
]

display(lentos)

print("Quantidade:", lentos.shape[0])

,id_chamado,data_abertura,setor,categoria,prioridade,status,tempo_resolucao_horas,satisfacao,reaberto,analista
2,CH003,2026-08-21,Biblioteca,Impressora,Baixa,Resolvido,30.0,3.0,Sim,Carla
7,CH008,2026-08-23,Biblioteca,Sistema lento,Baixa,Resolvido,45.0,4.0,Não,Diego
15,CH016,2026-08-27,Financeiro,Acesso,Baixa,Resolvido,52.0,2.0,Sim,Diego
17,CH018,2026-08-28,Laboratório,Sistema lento,Média,Resolvido,120.0,1.0,Sim,Bruno

Quantidade: 4

In [15]:
rede_acesso = df[
    df["categoria"].isin(["Rede", "Acesso"])
]

display(rede_acesso)

print("Quantidade:", rede_acesso.shape[0])

,id_chamado,data_abertura,setor,categoria,prioridade,status,tempo_resolucao_horas,satisfacao,reaberto,analista
0,CH001,2026-08-20,Financeiro,Acesso,Alta,Resolvido,3.5,5.0,Não,Ana
4,CH005,2026-08-22,RH,Acesso,Média,Em andamento,NaN,NaN,Não,Diego
5,CH006,2026-08-22,Acadêmico,Rede,Alta,Resolvido,9.5,2.0,Sim,Bruno
9,CH010,2026-08-24,Laboratório,Rede,Crítica,Resolvido,6.0,2.0,Sim,Bruno
11,CH012,2026-08-25,Acadêmico,Acesso,Baixa,Resolvido,10.0,5.0,Não,Diego
12,CH013,2026-08-26,Biblioteca,Rede,Média,Resolvido,18.0,4.0,Não,Ana
15,CH016,2026-08-27,Financeiro,Acesso,Baixa,Resolvido,52.0,2.0,Sim,Diego

Quantidade: 7

In [16]:
df["data_abertura"] = pd.to_datetime(
    df["data_abertura"]
)

In [17]:
df["tempo_dias"] = (
    df["tempo_resolucao_horas"] / 24
)

In [18]:
media = (
    df.groupby("categoria")[
        "tempo_resolucao_horas"
    ]
    .mean()
    .sort_values(ascending=False)
)

print(media)

categoria
Sistema lento      47.750000
Impressora         30.000000
Acesso             21.833333
Hardware           18.000000
Rede               11.166667
Erro de sistema     4.000000
Name: tempo_resolucao_horas, dtype: float64